/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalpage;
import CONFIG.DBCONNECTOR;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import java.text.*; 
import java.awt.print.*;
import javax.swing.JTable;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;
public class addbook extends javax.swing.JInternalFrame {
DefaultTableModel model;
    /**
     * Creates new form dashabord
     */
    public addbook() {
        initComponents();
        
         displayData();
          this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
        
    }
  public void reset(){
   EN.setText("");
   EBT.setText("");
   EG.setSelectedItem("0");
   ED.setText("");
   QUANT.setText("");
   }
     public void search(String str){
    model = (DefaultTableModel) BOOKDET.getModel();
    TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(model);
    BOOKDET.setRowSorter(trs);
    trs.setRowFilter(RowFilter.regexFilter(str));
    }
    
    public void displayData(){
        try{
       
            DBCONNECTOR dbc = new DBCONNECTOR();
            ResultSet rs = dbc.getData("SELECT * FROM book_details");
            BOOKDET.setModel(DbUtils.resultSetToTableModel(rs));
       
        }catch(SQLException ex){
            System.out.println("Error Message: "+ex);
       
        }
    
     }
    public void filltable () throws SQLException{
        try{
            DBCONNECTOR dbc = new DBCONNECTOR();
            ResultSet rs = dbc.getData("SELECT * FROM book_details");
            BOOKDET.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(SQLException ex){
        
        }
    
    }
     public boolean validation(){
  String isbn= EN.getText();
String tittle= EBT.getText();
String edition= ED.getText();
String quantity= ED.getText();
 if (isbn.equals("")){
 JOptionPane.showMessageDialog(this, "PLEASE ENTER ISBN");
 return false;
 }
 if(tittle.equals("")){
 JOptionPane.showMessageDialog(this, "PLEASE ENTER BOOK TITTLE");
 return false;
 }     
 if(edition.equals("")){
 JOptionPane.showMessageDialog(this, "PLEASE ENTER EDITION");
 return false;
 }    
   if(quantity.equals("")){
 JOptionPane.showMessageDialog(this, "PLEASE ENTER QUANTITY");
 return false;
 }      
   return true;  
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        EN = new app.bolivia.swing.JCTextField();
        jLabel1 = new javax.swing.JLabel();
        EBT = new app.bolivia.swing.JCTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ED = new app.bolivia.swing.JCTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        QUANT = new app.bolivia.swing.JCTextField();
        DELETE = new necesario.RSMaterialButtonCircle();
        ADD = new necesario.RSMaterialButtonCircle();
        UPDATE = new necesario.RSMaterialButtonCircle();
        line = new javax.swing.JLabel();
        line1 = new javax.swing.JLabel();
        line3 = new javax.swing.JLabel();
        line4 = new javax.swing.JLabel();
        EG = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        BOOKDET = new rojeru_san.complementos.RSTableMetro();
        search = new app.bolivia.swing.JCTextField();
        rSMaterialButtonCircle2 = new necesario.RSMaterialButtonCircle();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 58, 140));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(204, 0, 0));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EN.setBackground(new java.awt.Color(204, 0, 0));
        EN.setBorder(null);
        EN.setForeground(new java.awt.Color(153, 255, 153));
        EN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EN.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        EN.setOpaque(false);
        EN.setPlaceholder("ENTER ISBN");
        jPanel10.add(EN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 270, -1));

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("ISBN:");
        jPanel10.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 160, 32));

        EBT.setBackground(new java.awt.Color(204, 0, 0));
        EBT.setBorder(null);
        EBT.setForeground(new java.awt.Color(153, 255, 153));
        EBT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EBT.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        EBT.setOpaque(false);
        EBT.setPlaceholder("ENTER BOOBK TITTLE");
        EBT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EBTKeyReleased(evt);
            }
        });
        jPanel10.add(EBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 270, -1));

        jLabel3.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("BOOK TITTLE:");
        jPanel10.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 160, 32));

        jLabel4.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("GENRE:");
        jPanel10.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 160, 32));

        ED.setBackground(new java.awt.Color(204, 0, 0));
        ED.setBorder(null);
        ED.setForeground(new java.awt.Color(153, 255, 153));
        ED.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ED.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        ED.setOpaque(false);
        ED.setPlaceholder("ENTER EDITION");
        ED.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EDKeyTyped(evt);
            }
        });
        jPanel10.add(ED, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 270, -1));

        jLabel5.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("EDITION:");
        jPanel10.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 160, 32));

        jLabel6.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("QUANTITY:");
        jPanel10.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 160, 32));

        QUANT.setBackground(new java.awt.Color(204, 0, 0));
        QUANT.setBorder(null);
        QUANT.setForeground(new java.awt.Color(153, 255, 153));
        QUANT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        QUANT.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        QUANT.setOpaque(false);
        QUANT.setPlaceholder("ENTER QUANTITY");
        QUANT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                QUANTKeyPressed(evt);
            }
        });
        jPanel10.add(QUANT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 270, -1));

        DELETE.setText("DELETE");
        DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEActionPerformed(evt);
            }
        });
        jPanel10.add(DELETE, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 110, 59));

        ADD.setText("ADD");
        ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDActionPerformed(evt);
            }
        });
        jPanel10.add(ADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 100, 59));

        UPDATE.setText("UPDATE");
        UPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATEActionPerformed(evt);
            }
        });
        jPanel10.add(UPDATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 100, 59));

        line.setForeground(new java.awt.Color(25, 20, 20));
        line.setText("_____________________________________________");
        jPanel10.add(line, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 290, 30));

        line1.setForeground(new java.awt.Color(25, 20, 20));
        line1.setText("_____________________________________________");
        jPanel10.add(line1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 290, 30));

        line3.setForeground(new java.awt.Color(25, 20, 20));
        line3.setText("_____________________________________________");
        jPanel10.add(line3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 290, 30));

        line4.setForeground(new java.awt.Color(25, 20, 20));
        line4.setText("_____________________________________________");
        jPanel10.add(line4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 290, 30));

        EG.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SCI-FI", "HORROR", "MYSTERY", "NOVEL", "FANTASY", "MATHIMATICS", "SCIENCE", "BIOLOGY", "TECHNOLOGY", "" }));
        jPanel10.add(EG, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 280, 30));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 540));

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/book (7).png"))); // NOI18N
        jLabel2.setText("ADD BOOK");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 280, 70));

        BOOKDET.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        BOOKDET.setColorBackgoundHead(new java.awt.Color(204, 0, 0));
        BOOKDET.setFuenteHead(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        BOOKDET.setGrosorBordeFilas(0);
        BOOKDET.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BOOKDETMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(BOOKDET);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 530, 400));

        search.setBorder(null);
        search.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        search.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        search.setPlaceholder("SEARCH");
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 340, 20));

        rSMaterialButtonCircle2.setBackground(new java.awt.Color(204, 0, 0));
        rSMaterialButtonCircle2.setText("PRINT");
        rSMaterialButtonCircle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle2ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonCircle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, 110, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BOOKDETMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BOOKDETMouseClicked
      int rowIndex = BOOKDET.getSelectedRow();
        if(rowIndex <0){
        
        }else{
        TableModel model = BOOKDET.getModel();

        EN.setText(""+model.getValueAt(rowIndex, 0));
        EBT.setText(""+model.getValueAt(rowIndex, 1));
        EG.setSelectedItem(""+model.getValueAt(rowIndex, 2));
        ED.setText(""+model.getValueAt(rowIndex, 3));
        QUANT.setText(""+model.getValueAt(rowIndex, 4));
        }
    }//GEN-LAST:event_BOOKDETMouseClicked

    private void ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDActionPerformed
        if(validation()== true){
            DBCONNECTOR dbc = new DBCONNECTOR();
        dbc.insertData("INSERT INTO book_details ( ISBN, TITTLE, GENRE, EDITION, QUANTITY) "
                + "VALUES ('"+EN.getText()+"','"+EBT.getText()+"','"+EG.getSelectedItem()+"','"+ED.getText()+"','"+QUANT.getText()+"')");
        displayData();
        reset();
        }     
       
    }//GEN-LAST:event_ADDActionPerformed

    private void UPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEActionPerformed
      if(validation()== true){
      
      DBCONNECTOR dbc = new DBCONNECTOR();
        int num = dbc.updateData("UPDATE book_details SET TITTLE "
                + "= '"+EBT.getText()+"', GENRE = '"+EG.getSelectedItem()+"', EDITION "
                        + "= '"+ED.getText()+"', QUANTITY = '"+QUANT.getText()+"' WHERE ISBN = '"+EN.getText()+"'");
        if(num ==0){
        
        }else{
        JOptionPane.showMessageDialog(null, "updated successfully");
        displayData();
        reset();
        }
      
      }
    }//GEN-LAST:event_UPDATEActionPerformed

    private void DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEActionPerformed
       int rowIndex = BOOKDET.getSelectedRow();
       if(rowIndex < 0){
           JOptionPane.showMessageDialog(null, "Please select a data first");
       }else{
            TableModel model = BOOKDET.getModel();
            Object value = model.getValueAt(rowIndex, 0);
            String ISBN = value.toString();
             int a=JOptionPane.showConfirmDialog(null,"Are you sure?");  
                    if(a==JOptionPane.YES_OPTION){  
                            DBCONNECTOR dbc = new DBCONNECTOR();
                            dbc.deleteData1(Integer.parseInt(ISBN));
                            displayData();
                            reset();
                    }    
       }
    }//GEN-LAST:event_DELETEActionPerformed

    private void EDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EDKeyTyped
        char c =evt.getKeyChar();
        if(Character.isLetter(c)){
        ED.setEditable(false);
        JOptionPane.showMessageDialog(this, "Please enter number only");
        }else{
        ED.setEditable(true);
        
        }
    }//GEN-LAST:event_EDKeyTyped

    private void QUANTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QUANTKeyPressed
          char c =evt.getKeyChar();
        if(Character.isLetter(c)){
        ED.setEditable(false);
        JOptionPane.showMessageDialog(this, "Please enter number only");
        }else{
        ED.setEditable(true);
        
        }
    }//GEN-LAST:event_QUANTKeyPressed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        String seachst = search.getText();
        search(seachst);
    }//GEN-LAST:event_searchKeyReleased

    private void rSMaterialButtonCircle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle2ActionPerformed
     MessageFormat head = new MessageFormat("BOOKS");
        MessageFormat FOOT = new MessageFormat("Page{0, number , integer}");

        try {
            BOOKDET.print(JTable.PrintMode.NORMAL, head, FOOT);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, "cannot print");
        }
    }//GEN-LAST:event_rSMaterialButtonCircle2ActionPerformed

    private void EBTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EBTKeyReleased
       int pos = EBT.getCaretPosition();
        EBT.setText(EBT.getText().toUpperCase());
        EBT.setCaretPosition(pos);
        
    }//GEN-LAST:event_EBTKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private necesario.RSMaterialButtonCircle ADD;
    private rojeru_san.complementos.RSTableMetro BOOKDET;
    private necesario.RSMaterialButtonCircle DELETE;
    private app.bolivia.swing.JCTextField EBT;
    private app.bolivia.swing.JCTextField ED;
    private javax.swing.JComboBox<String> EG;
    private app.bolivia.swing.JCTextField EN;
    private app.bolivia.swing.JCTextField QUANT;
    private necesario.RSMaterialButtonCircle UPDATE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel line;
    private javax.swing.JLabel line1;
    private javax.swing.JLabel line3;
    private javax.swing.JLabel line4;
    private necesario.RSMaterialButtonCircle rSMaterialButtonCircle2;
    private app.bolivia.swing.JCTextField search;
    // End of variables declaration//GEN-END:variables
}
