/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalpage;
import CONFIG.DBCONNECTOR;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import net.proteanit.sql.DbUtils;
public class addstudent extends javax.swing.JInternalFrame {

    /**
     * Creates new form dashabord
     */
    public addstudent() {
        initComponents();
        
         displayData();
          this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
        
    }
  public void reset(){
  ID.setText("");
      EN.setText("");
   ELN.setText("");
   EC.setText("");
   EY.setText("");
   ECT.setText("");
   }
    
    
      public void displayData(){
        try{
       
            DBCONNECTOR dbc = new DBCONNECTOR();
            ResultSet rs = dbc.getData("SELECT * FROM student_details");
            studentdet.setModel(DbUtils.resultSetToTableModel(rs));
       
        }catch(SQLException ex){
            System.out.println("Error Message: "+ex);
       
        }
    
     }
    public void filltable () throws SQLException{
        try{
            DBCONNECTOR dbc = new DBCONNECTOR();
            ResultSet rs = dbc.getData("SELECT * FROM student_details");
            studentdet.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(SQLException ex){
        
        
        
        
        
        }
    
    }
    
     public boolean validation(){
  String name= EN.getText();
String lastname= ELN.getText();
String course= EC.getText();
String year= EY.getText();
String contact= ECT.getText();
 if (name.equals("")){
 JOptionPane.showMessageDialog(this, "PLEASE ENTER NAME");
 return false;
 }
 if(lastname.equals("")){
 JOptionPane.showMessageDialog(this, "PLEASE ENTER LASTNAME");
 return false;
 }
if(course.equals("")){
 JOptionPane.showMessageDialog(this, "PLEASE ENTER COURSE");
 return false;
 }     
 if(year.equals("")){
 JOptionPane.showMessageDialog(this, "PLEASE ENTER YEAR");
 return false;
 }    
   if(contact.equals("")){
 JOptionPane.showMessageDialog(this, "PLEASE ENTER CONTACT");
 return false;
 }      
   return true;  
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        ID = new app.bolivia.swing.JCTextField();
        jLabel1 = new javax.swing.JLabel();
        EN = new app.bolivia.swing.JCTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ELN = new app.bolivia.swing.JCTextField();
        EC = new app.bolivia.swing.JCTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        EY = new app.bolivia.swing.JCTextField();
        DELETE = new necesario.RSMaterialButtonCircle();
        ADD = new necesario.RSMaterialButtonCircle();
        UPDATE = new necesario.RSMaterialButtonCircle();
        ECT = new app.bolivia.swing.JCTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentdet = new rojeru_san.complementos.RSTableMetro();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 58, 140));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(204, 0, 0));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ID.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        ID.setPlaceholder("ENTER ID");
        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });
        jPanel10.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 270, -1));

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("ID:");
        jPanel10.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 120, 32));

        EN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EN.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        EN.setPlaceholder("ENTER NAME");
        jPanel10.add(EN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 270, -1));

        jLabel3.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("NAME:");
        jPanel10.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 120, 32));

        jLabel4.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("LASTNAME:");
        jPanel10.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 120, 32));

        ELN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ELN.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        ELN.setPlaceholder("ENTER LASTNAME");
        jPanel10.add(ELN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 270, -1));

        EC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EC.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        EC.setPlaceholder("ENTER COURSE");
        EC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ECKeyTyped(evt);
            }
        });
        jPanel10.add(EC, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 270, -1));

        jLabel5.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("COURSE:");
        jPanel10.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 120, 32));

        jLabel6.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("YEAR:");
        jPanel10.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 120, 32));

        EY.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EY.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        EY.setPlaceholder("ENTER YEAR");
        EY.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EYKeyPressed(evt);
            }
        });
        jPanel10.add(EY, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 270, -1));

        DELETE.setText("DELETE");
        DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEActionPerformed(evt);
            }
        });
        jPanel10.add(DELETE, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 459, 100, 50));

        ADD.setText("ADD");
        ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDActionPerformed(evt);
            }
        });
        jPanel10.add(ADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 459, 100, 50));

        UPDATE.setText("UPDATE");
        UPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATEActionPerformed(evt);
            }
        });
        jPanel10.add(UPDATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 459, 100, 50));

        ECT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ECT.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        ECT.setPlaceholder("ENTER CONTACT");
        ECT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ECTActionPerformed(evt);
            }
        });
        ECT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ECTKeyPressed(evt);
            }
        });
        jPanel10.add(ECT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 270, -1));

        jLabel7.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("CONTACT:");
        jPanel10.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 110, 32));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 540));

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/graduation.png"))); // NOI18N
        jLabel2.setText("ADD STUDENT");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 350, 60));

        studentdet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        studentdet.setColorBackgoundHead(new java.awt.Color(204, 0, 0));
        studentdet.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        studentdet.setFuenteHead(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        studentdet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentdetMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(studentdet);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 530, 460));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentdetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentdetMouseClicked
      int rowIndex = studentdet.getSelectedRow();
        if(rowIndex <0){
        
        }else{
        TableModel model = studentdet.getModel();

        ID.setText(""+model.getValueAt(rowIndex, 0));
        EN.setText(""+model.getValueAt(rowIndex, 1));
        ELN.setText(""+model.getValueAt(rowIndex, 2));
        EC.setText(""+model.getValueAt(rowIndex, 3));
        EY.setText(""+model.getValueAt(rowIndex, 4));
         ECT.setText(""+model.getValueAt(rowIndex, 4));
        }
    }//GEN-LAST:event_studentdetMouseClicked

    private void ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDActionPerformed
        if(validation()== true){
       DBCONNECTOR dbc = new DBCONNECTOR();
        dbc.insertData("INSERT INTO student_details ( NAME, LASTNAME, COURSE, YEAR, CONTACT) "
                + "VALUES ('"+EN.getText()+"', '"+ELN.getText()+"','"+EC.getText()+"','"+EY.getText()+"','"+ECT.getText()+"')");
        displayData();
        reset(); 
        JOptionPane.showMessageDialog(this, "ADDED SUCCESSFULLY");
        }
    }//GEN-LAST:event_ADDActionPerformed

    private void UPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEActionPerformed
      if(validation()== true){
      
     DBCONNECTOR dbc = new DBCONNECTOR();
        int num = dbc.updateData("UPDATE student_details "
       + "SET NAME = '"+EN.getText()+"', LASTNAME='"+ELN.getText()+"', "
                        + "COURSE ='"+EC.getText()+"', YEAR='"+EY.getText()+"', CONTACT='"+ECT.getText()+"'  "
                                + "WHERE ID = '"+ID.getText()+"'");
       
        if(num == 0){
            JOptionPane.showMessageDialog(null, "Updated FAILED!");
        }else{
           JOptionPane.showMessageDialog(null, "Updated Successfully!");
           displayData();
           reset();
        }
      }
    }//GEN-LAST:event_UPDATEActionPerformed

    private void DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEActionPerformed
     int rowIndex = studentdet.getSelectedRow();
       if(rowIndex < 0){
           JOptionPane.showMessageDialog(null, "Please select a data first");
       }else{
            TableModel model = studentdet.getModel();
            Object value = model.getValueAt(rowIndex, 0);
            String ID = value.toString();
             int a=JOptionPane.showConfirmDialog(null,"Are you sure?");  
                    if(a==JOptionPane.YES_OPTION){  
                            DBCONNECTOR dbc = new DBCONNECTOR();
                            dbc.deleteData(Integer.parseInt(ID));
                            displayData();
                            reset();
                            JOptionPane.showMessageDialog(this, "DELETED SUCCESSFULL");
                    }    
       }
    }//GEN-LAST:event_DELETEActionPerformed

    private void ECKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ECKeyTyped
   
    }//GEN-LAST:event_ECKeyTyped

    private void EYKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EYKeyPressed
          char c =evt.getKeyChar();
        if(Character.isLetter(c)){
        EC.setEditable(false);
        JOptionPane.showMessageDialog(this, "Please enter number only");
        }else{
        EC.setEditable(true);
        
        }
    }//GEN-LAST:event_EYKeyPressed

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDActionPerformed

    private void ECTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ECTKeyPressed
      char c =evt.getKeyChar();
        if(Character.isLetter(c)){
        EC.setEditable(false);
        JOptionPane.showMessageDialog(this, "Please enter number only");
        }else{
        EC.setEditable(true);
        } 
    }//GEN-LAST:event_ECTKeyPressed

    private void ECTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ECTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ECTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private necesario.RSMaterialButtonCircle ADD;
    private necesario.RSMaterialButtonCircle DELETE;
    private app.bolivia.swing.JCTextField EC;
    private app.bolivia.swing.JCTextField ECT;
    private app.bolivia.swing.JCTextField ELN;
    private app.bolivia.swing.JCTextField EN;
    private app.bolivia.swing.JCTextField EY;
    private app.bolivia.swing.JCTextField ID;
    private necesario.RSMaterialButtonCircle UPDATE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane1;
    private rojeru_san.complementos.RSTableMetro studentdet;
    // End of variables declaration//GEN-END:variables
}
